-- (plugins)
require('plugins.lspconfig')
require('plugins.neo-tree')
require('plugins.dashboard')
require('plugins.twilight')
require('plugins.treesitter')
require('plugins.checkmate')
require('plugins.themery')
require('plugins.mini')
require('plugins.nvim-tree')
require('plugins.neovim-sm')
require('plugins.lualine')
require('plugins.lazygit')
require('plugins.notify')
-- require configs
require('config.dashboard-nvim')
require('config.keymap')
require('config.options')
